dataset_name: "potsdam"
model_name: "ViT-L/14"


semantic_templates: "C:/Users/UU/Desktop/SDCI/template/image_template.txt"
potsdam_root: "E:/ISPRS/potsdam_RGB/val/potsdam_test_512_snapped/images"
img_name_list_path: "E:/ISPRS/potsdam_RGB/val/potsdam_test_512_snapped/potsdam_2016_val.txt"
label_root: "E:/ISPRS/potsdam_RGB/val/potsdam_test_512_snapped/labels-255"

logit_scale: 50
score_threshold: 0.0
bkg_thre: 0
is_normalize: True
ignore_labels: 255
dino_version: 2