dataset_name: "vaihingen"
model_name: "ViT-L/14"


semantic_templates: "C:/Users/UU/Desktop/SDCI/template/image_template.txt"
vaihingen_root: "E:/ISPRS/vaihingen_IRRG/val/vaihingen_512_snapped/images"
img_name_list_path: "E:/ISPRS/vaihingen_IRRG/val/vaihingen_512_snapped/vaihingen_398_val.txt"
label_root: "E:/ISPRS/vaihingen_IRRG/val/vaihingen_512_snapped/labels-255"

logit_scale: 50
score_threshold: 0.0
bkg_thre: 0
is_normalize: True
ignore_labels: 255
dino_version: 2